require 'rails/generators'

class TestAppGenerator < Rails::Generators::Base

  def add_gems
    gem 'blacklight'
    gem 'hydra-head', '9.0.0.rc1'
    Bundler.with_clean_env do
      run "bundle install"
    end
  end

  def run_blacklight_generator
    say_status("warning", "GENERATING BL", :yellow)
    generate "blacklight:install --devise"
    gsub_file "app/controllers/application_controller.rb", "layout 'blacklight'", "layout 'application'"
  end

  def run_hydra_generator
    say_status("warning", "GENERATING Hydra", :yellow)
    generate "hydra:head -f"
  end

  def run_migrations
    rake "db:migrate"
    rake "db:test:prepare"
  end

  def add_route
    insert_into_file "config/routes.rb", after: '.draw do' do
      "\n  mount HydraEditor::Engine => \"/\"\n"
    end
  end

  # def remove_devise_cruft
  #   remove_file "spec/factories/users.rb" # generated by devise
  #   remove_file "spec/models/user_spec.rb" # generated by devise
  # end

  def add_create_ability
    # Required for hydra-head 7+
    insert_into_file "app/models/ability.rb", after: 'custom_permissions' do
      "\n    can :create, :all if user_groups.include? 'registered'\n"
    end

  end

end
